[package]
name = "bolt"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.1"
chrono = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.7", package = "gtk4" }
once_cell = "1.19"
r2d2 = "0.8"
r2d2_sqlite = "0.23"
rusqlite = "0.30"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha1 = "0.10"
ureq = "2.9"

[dependencies.adw]
package = "libadwaita"
version = "0.5"
features = ["v1_4"]
